Repository Kggupta/cs446-project, pull requests merged in 2024-03, with the labels that each got.

#29 Fix account already exists when generic error occurs
  app/app/src/main/java/com/example/clubwat/viewmodels/SignUpViewModel.kt
  timelog.md
Labels: bug

#31 Generic error message for when invalid email or edge case occurs
  app/app/src/main/java/com/example/clubwat/viewmodels/SignUpViewModel.kt
Labels: bug

#33 Home page with events
  app/app/build.gradle.kts
  app/app/src/main/java/com/example/clubwat/model/Event.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/HomeViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/SignUpViewModel.kt
  app/app/src/main/java/com/example/clubwat/views/EventItem.kt
  app/app/src/main/java/com/example/clubwat/views/HomeView.kt
  app/app/src/main/java/com/example/clubwat/views/NavigationBar/NavBar.kt
  app/app/src/main/java/com/example/clubwat/views/SearchView.kt
  app/gradle.properties
  server/src/requests/Event.rest
  server/src/requests/Login.rest
Labels: enhancement

#36 CWAT-53275978-Club-Discussions-FE
  app/app/build.gradle.kts
  app/app/src/main/java/com/example/clubwat/model/Data.kt
  app/app/src/main/java/com/example/clubwat/model/DiscussionData.kt
  app/app/src/main/java/com/example/clubwat/model/NetworkResult.kt
  app/app/src/main/java/com/example/clubwat/model/SendDiscusionMessageRequest.kt
  app/app/src/main/java/com/example/clubwat/model/UserX.kt
  app/app/src/main/java/com/example/clubwat/repository/DiscussionRepository.kt
  app/app/src/main/java/com/example/clubwat/repository/UserRepository.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ClubDetailsViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ClubDiscussionViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/CodeVerificationViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ForYouViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/HomeViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/LoginViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ProfileViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/SearchViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/SignUpViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/ClubDetailsViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/ClubDiscussionViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/CodeVerificationViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/ForYouViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/HomeViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/LoginViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/ProfileViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/SearchViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/SignUpViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/views/ClubDetailsView.kt
  app/app/src/main/java/com/example/clubwat/views/ClubDiscussionView.kt
  app/app/src/main/java/com/example/clubwat/views/MainActivity.kt
  app/gradle.properties
  server/src/requests/Club.rest
  server/src/requests/ClubDiscussion.rest
Labels: enhancement

#38 UI Cleanup of NavBars for prototype demo
  app/app/src/main/java/com/example/clubwat/model/ClubDiscussion.kt
  app/app/src/main/java/com/example/clubwat/model/DiscussionData.kt
  app/app/src/main/java/com/example/clubwat/model/MessageData.kt
  app/app/src/main/java/com/example/clubwat/model/UserProfile.kt
  app/app/src/main/java/com/example/clubwat/repository/DiscussionRepository.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ClubDiscussionViewModel.kt
  app/app/src/main/java/com/example/clubwat/views/ClubDetailsView.kt
  app/app/src/main/java/com/example/clubwat/views/ClubDiscussionView.kt
  app/app/src/main/java/com/example/clubwat/views/HomeView.kt
  app/app/src/main/java/com/example/clubwat/views/LoginView.kt
  app/app/src/main/java/com/example/clubwat/views/ProfileView.kt
  app/app/src/main/java/com/example/clubwat/views/SearchView.kt
  timelog.md
Labels: bug

#39 CWAT-52905350: Get For You Clubs Endpoint
  server/database.dbml
  server/prisma/migrations/20240307181922_/migration.sql
  server/prisma/schema.prisma
  server/src/api/ClubRoutes.ts
  server/src/requests/Club.rest
  timelog.md
Labels: enhancement

#40 Club details update, share backend
  app/app/src/main/java/com/example/clubwat/model/ClubDetails.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/HomeViewModel.kt
  app/app/src/main/java/com/example/clubwat/views/ClubDetailsView.kt
  app/app/src/main/java/com/example/clubwat/views/ClubDiscussionView.kt
  app/app/src/main/java/com/example/clubwat/views/HomeView.kt
  app/app/src/main/java/com/example/clubwat/views/MainActivity.kt
  app/app/src/main/java/com/example/clubwat/views/ProfileView.kt
  server/database.dbml
  server/prisma/migrations/20240307230721_/migration.sql
  server/prisma/migrations/20240308002928_/migration.sql
  server/prisma/migrations/20240308011750_/migration.sql
  server/prisma/schema.prisma
  server/src/api/ClubRoutes.ts
  server/src/api/ShareRoutes.ts
  server/src/api/UserRoutes.ts
  server/src/api/index.ts
  server/src/lib/EmailService.ts
  server/src/requests/Login.rest
  server/src/requests/Share.rest
  timelog.md
Labels: enhancement

#41 user inbox + notifications, user friendship get endpoint
  app/app/build.gradle.kts
  app/app/src/main/java/com/example/clubwat/model/Notification.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/InboxViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/InboxViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/views/CodeVerificationView.kt
  app/app/src/main/java/com/example/clubwat/views/HomeView.kt
  app/app/src/main/java/com/example/clubwat/views/InboxView.kt
  app/app/src/main/java/com/example/clubwat/views/MainActivity.kt
  app/app/src/main/java/com/example/clubwat/views/NavigationBar/NavBar.kt
  app/app/src/main/java/com/example/clubwat/views/SearchView.kt
  app/gradle.properties
  server/database.dbml
  server/prisma/migrations/20240308172205_/migration.sql
  server/prisma/schema.prisma
  server/src/api/FriendRoutes.ts
  server/src/api/ShareRoutes.ts
  server/src/api/index.ts
  timelog.md
Labels: enhancement

#42 Event details, share event, share club
  app/app/build.gradle.kts
  app/app/src/main/java/com/example/clubwat/model/Event.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ClubDetailsViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/EventDetailsViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/SearchViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/EventDetailsViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/views/ClubDetailsView.kt
  app/app/src/main/java/com/example/clubwat/views/EventDetailsView.kt
  app/app/src/main/java/com/example/clubwat/views/EventItem.kt
  app/app/src/main/java/com/example/clubwat/views/InboxView.kt
  app/app/src/main/java/com/example/clubwat/views/MainActivity.kt
  app/app/src/main/java/com/example/clubwat/views/NavigationBar/NavBar.kt
  app/app/src/main/java/com/example/clubwat/views/ShareDialog.kt
  app/gradle.properties
  server/src/api/EventRoutes.ts
  server/src/api/ShareRoutes.ts
  server/src/lib/EmailService.ts
  server/src/requests/Share.rest
  timelog.md
Labels: enhancement

#44 30 second wait time for resend button
  app/app/src/main/java/com/example/clubwat/views/CodeVerificationView.kt
  timelog.md
Labels: bug

#45 club user management flow, club settings page for admins
  app/app/build.gradle.kts
  app/app/src/main/java/com/example/clubwat/model/ClubDetails.kt
  app/app/src/main/java/com/example/clubwat/model/ClubMemberList.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ClubDetailsViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ClubManagementViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ClubUserManagementViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/ClubManagementViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/ClubUserManagementViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/views/ClubDetailsView.kt
  app/app/src/main/java/com/example/clubwat/views/ClubManagementView.kt
  app/app/src/main/java/com/example/clubwat/views/ClubUserManagementView.kt
  app/app/src/main/java/com/example/clubwat/views/DetailItem.kt
  app/app/src/main/java/com/example/clubwat/views/EventDetailsView.kt
  app/app/src/main/java/com/example/clubwat/views/MainActivity.kt
  app/gradle.properties
  server/database.dbml
  server/prisma/migrations/20240310203605_/migration.sql
  server/prisma/migrations/20240310203636_/migration.sql
  server/prisma/migrations/20240310225525_/migration.sql
  server/prisma/schema.prisma
  server/src/api/ClubAdminRoutes.ts
  server/src/api/ClubRoutes.ts
  server/src/lib/EmailService.ts
  server/src/requests/Club.rest
  server/src/requests/ClubAdmin.rest
  server/src/requests/Login.rest
  server/src/requests/User.rest
  timelog.md
Labels: enhancement

#46 CWAT-52905562: Added friend routes
  server/database.dbml
  server/prisma/migrations/20240311170844_updated_friend_table/migration.sql
  server/prisma/schema.prisma
  server/src/api/FriendRoutes.ts
  server/src/requests/Club.rest
  server/src/requests/ClubDiscussion.rest
  server/src/requests/Event.rest
  server/src/requests/Friend.rest
  server/src/requests/Register.rest
  server/src/requests/Share.rest
  timelog.md
Labels: enhancement

#47 For You Page
  app/app/build.gradle.kts
  app/app/src/main/java/com/example/clubwat/model/Club.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ForYouViewModel.kt
  app/app/src/main/java/com/example/clubwat/views/ClubUserManagementView.kt
  app/app/src/main/java/com/example/clubwat/views/CodeVerificationView.kt
  app/app/src/main/java/com/example/clubwat/views/ForYouView.kt
  app/gradle.properties
  timelog.md
Labels: enhancement

#48 fix default create_date for notifications
  app/app/src/main/java/com/example/clubwat/viewmodels/InboxViewModel.kt
  app/app/src/main/java/com/example/clubwat/views/ClubDetailsView.kt
  server/prisma/migrations/20240311190725_/migration.sql
  server/prisma/migrations/20240311191159_/migration.sql
  server/prisma/schema.prisma
  server/src/api/ClubAdminRoutes.ts
  server/src/api/ShareRoutes.ts
  timelog.md
Labels: bug

#49 APIs for User Interests
  server/src/api/UserInterestRoutes.ts
  server/src/api/index.ts
  server/src/requests/UserInterest.rest
  timelog.md
Labels: enhancement

#50 Update club events
  app/app/src/main/java/com/example/clubwat/views/ClubUserManagementView.kt
  deliverables/CS446_D3_Demo_Summary.pdf
  server/database.dbml
  server/package.json
  server/prisma/migrations/20240312210017_/migration.sql
  server/prisma/schema.prisma
  server/src/api/ClubEventRoutes.ts
  server/src/api/ClubRoutes.ts
  server/src/api/EventRoutes.ts
  server/src/api/UserRoutes.ts
  server/src/requests/Login.rest
  server/src/requests/User.rest
  timelog.md
Labels: enhancement

#51 Event Creation
  app/app/build.gradle.kts
  app/app/src/main/java/com/example/clubwat/viewmodels/AddEventViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/AddEventViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/views/AddEventView.kt
  app/app/src/main/java/com/example/clubwat/views/ClubDetailsView.kt
  app/app/src/main/java/com/example/clubwat/views/ClubManagementView.kt
  app/app/src/main/java/com/example/clubwat/views/DateTimePickerView.kt
  app/app/src/main/java/com/example/clubwat/views/MainActivity.kt
  app/gradle.properties
  server/src/api/ClubEventRoutes.ts
  server/src/requests/ClubEvent.rest
  timelog.md
Labels: enhancement

#52 Remove is approved from update club ep
  server/src/api/ClubRoutes.ts
Labels: bug

#53 Edit Clubs
  app/app/build.gradle.kts
  app/app/src/main/java/com/example/clubwat/viewmodels/EditClubDetailsViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/factories/EditClubDetailsViewModelFactory.kt
  app/app/src/main/java/com/example/clubwat/views/AddEventView.kt
  app/app/src/main/java/com/example/clubwat/views/ClubManagementView.kt
  app/app/src/main/java/com/example/clubwat/views/DateTimePickerView.kt
  app/app/src/main/java/com/example/clubwat/views/EditClubDetailsView.kt
  app/app/src/main/java/com/example/clubwat/views/MainActivity.kt
  app/gradle.properties
  server/src/api/ClubRoutes.ts
  server/src/requests/Login.rest
Labels: enhancement

#54 Added display club fair (spotlighted event) + special wusa club
  app/app/build.gradle.kts
  app/app/src/main/java/com/example/clubwat/viewmodels/ClubDetailsViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/HomeViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ProfileViewModel.kt
  app/app/src/main/java/com/example/clubwat/views/AddEventView.kt
  app/app/src/main/java/com/example/clubwat/views/ClubUserManagementView.kt
  app/app/src/main/java/com/example/clubwat/views/HomeView.kt
  app/gradle.properties
  server/database.dbml
  server/prisma/migrations/20240313185334_/migration.sql
  server/prisma/migrations/20240313194156_/migration.sql
  server/prisma/migrations/20240313194342_npx_prisma_generate/migration.sql
  server/prisma/schema.prisma
  server/src/api/EventRoutes.ts
  server/src/api/SpotlightRoutes.ts
  server/src/api/index.ts
  server/src/app.ts
  server/src/middlewares.ts
  server/src/requests/Club.rest
  server/src/requests/ClubAdmin.rest
  server/src/requests/Friend.rest
  server/src/requests/Spotlight.rest
  server/src/requests/User.rest
  timelog.md
Labels: enhancement

#56 Notify users when there's an upcoming event
  server/src/api/ClubEventRoutes.ts
  server/src/api/ClubRoutes.ts
  server/src/lib/EmailService.ts
  timelog.md
Labels: enhancement

#19 User Profile - Interests, Password, Friends
  app/app/build.gradle.kts
  app/app/src/main/java/com/example/clubwat/model/Interest.kt
  app/app/src/main/java/com/example/clubwat/ui/theme/Color.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ProfileViewModel.kt
  app/app/src/main/java/com/example/clubwat/views/ProfileView.kt
  app/app/src/main/java/com/example/clubwat/views/ProfileViewComponenets.kt
  app/gradle.properties
  server/src/api/FriendRoutes.ts
  server/src/api/UserInterestRoutes.ts
  server/src/api/UserRoutes.ts
  server/src/api/index.ts
  server/src/requests/Friend.rest
  server/src/requests/UserInterest.rest
  timelog.md
Labels: enhancement

#62 Club and Event Feedback
  app/app/build.gradle.kts
  app/app/src/main/java/com/example/clubwat/model/ClubDetails.kt
  app/app/src/main/java/com/example/clubwat/model/Event.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/ClubDetailsViewModel.kt
  app/app/src/main/java/com/example/clubwat/viewmodels/EventDetailsViewModel.kt
  app/app/src/main/java/com/example/clubwat/views/ClubDetailsView.kt
  app/app/src/main/java/com/example/clubwat/views/DetailItem.kt
  app/app/src/main/java/com/example/clubwat/views/EventDetailsView.kt
  app/app/src/main/java/com/example/clubwat/views/ProfileView.kt
  app/gradle.properties
  server/database.dbml
  server/prisma/migrations/20240318233622_/migration.sql
  server/prisma/schema.prisma
  server/src/api/ClubRoutes.ts
  server/src/api/EventRoutes.ts
  server/src/api/FeedbackRoutes.ts
  server/src/api/UserRoutes.ts
  server/src/api/index.ts
  timelog.md
Labels: enhancement

#71 Added D4
  deliverables/CS446_D4_Arch_Styles.pdf
  package-lock.json
Labels: documentation
